name: SyncChest
version: 1.1.1
description: Sync your Chests for Teamgames
website: http://dev.bukkit.org/bukkit-plugins/SyncChest/
author: Aubli
main: me.Aubli.SyncChest.SyncChest

commands:
    sc:
        description: SyncChest Commands!
        usage: |
               /<command>
               /<command> help
               /<command> tool
               /<command> status
               /<command> save
               /<command> reload
               /<command> open [MainChest-ID]
               /<command> main [amount]
               /<command> related [amount]
               /<command> link [RelatedChest-ID] [MainChest-ID]
               /<command> unlink [RelatedChest-ID] [MainChest-ID]